apiVersion: apps/v1 # Specifies the API version for this Kubernetes resource.
kind: Deployment
metadata:
  name: vocabulary-deployment

spec:
  template:
    metadata:
      labels:
        app: vocabulary
    spec:
      containers:
        - name: vocabulary-container
          image: vocabulary_web
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: vocabulary
