apiVersion: v1
kind: Secret
metadata:
  namespace: vocabulary
  name: data-secret

type: Opaque
data:
  MYSQL_ROOT_PASSWORD: SUJNLXZvY2FidWxhcnk3
  MYSQL_DATABASE: dm9jYWJ1bGFyeQ==
  MYSQL_USER: YmVuaXRv
  MYSQL_PASSWORD: YmVuaXRvX3ZvYzg5
