apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: vocabulary
    type: front-end

spec:
  containers:
  - name: web
    image: delormebenoit/vocabulary_web:v1.0
    ports:
      - containerPort: 8080
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
