apiVersion: v1
kind: Service
metadata:
  name: front-service

spec:
  selector:
    app: vocabulary
    type: front-end
  type: NodePort
  ports:
  - targetPort: 8080
    port: 80
    nodePort: 30008
