name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests and coverage
        run: |
          coverage run -m pytest
          coverage report -m
          coverage xml

      - name: Check coverage
        run: |
          COVERAGE_THRESHOLD=90
          coverage report -m | tail -n 1 | grep -oP "\d+%" > coverage.txt
          COVERAGE=$(cat coverage.txt | tr -d '%')
          if [ $COVERAGE -lt $COVERAGE_THRESHOLD ]; then
            echo "Coverage is below threshold ($COVERAGE_THRESHOLD%)"
            exit 1
          fi

      - name: Run pylint
        run: |
          pylint your_module.py

      - name: Run mypy
        run: |
          mypy your_module.py

